// auth
export const AUTH = {
  SET_TOKEN: "SET_TOKEN",
  AUTH_LOADING: "AUTH_LOADING",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  LOGOUT_USER: "LOGOUT_USER",
  SET_ERROR: "SET_ERROR",
}

// nav
export const OPEN_MENU = "OPEN_MENU";
export const CLOSE_MENU = "CLOSE_MENU";
export const REHYDRATE = "persist/REHYDRATE";

export const IMAGE_GROUP = {
  LOADING: "IMAGE_GROUP_LOADING",
  DID_LOAD: "IMAGE_GROUP_DID_LOAD",
  LOAD_ERROR: "IMAGE_GROUP_LOAD_ERROR",
  LOAD_PAGE: "IMAGE_GROUP_LOAD_PAGE",
  LOAD_GROUP: "IMAGE_GROUP_LOAD_GROUP",
  REFRESH_ITEM: "IMAGE_GROUP_REFRESH_ITEM",
  FORGET_ITEM: "IMAGE_GROUP_FORGET_ITEM",
  SET_INDEX: "IMAGE_GROUP_SET_INDEX",
}

export const USER = {
  LOADING: "USER_LOADING",
  DID_LOAD: "USER_DID_LOAD",
  LOAD_ERROR: "USER_LOAD_ERROR",
  SET_USERS: "USER_SET_USERS",
}

export const HIERARCHY = {
  INDEX: "HIERARCHY_INDEX",
  LOADING: "HIERARCHY_LOADING",
  DID_LOAD: "HIERARCHY_DID_LOAD",
  LOAD_INDEX: "HIERARCHY_LOAD_INDEX",
  SET_NODE: "HIERARCHY_SET_NODE",
  BROWSE_TO: "HIERARCHY_BROWSE_TO",
  LOAD_IMAGES_FOR_ID: "HIERARCHY_LOAD_IMAGES_FOR_ID",
  LOAD_ITEM: "HIERARCHY_LOAD_ITEM",
  FORGET_ITEM: "HIERARCHY_FORGET_ITEM",
  SET_GALLERY_MODE: "SET_GALLERY_MODE",
}

export const IMAGE = {
  LOADING: "IMAGE_LOADING",
  DID_LOAD: "IMAGE_DID_LOAD",
  LOAD_INDEX: "IMAGE_LOAD_INDEX",
  LOAD_PAGE: "IMAGE_LOAD_PAGE",
  SET_NODE: "IMAGE_SET_NODE",
  BROWSE_TO: "IMAGE_BROWSE_TO",
  LOAD_ITEM: "IMAGE_LOAD_ITEM",
  LOAD_STATS: "IMAGE_LOAD_STATS",
  UPDATE_ITEM: "IMAGE_UPDATE_ITEM",
  FORGET_ITEM: "IMAGE_FORGET_ITEM",
  LOAD_IMAGE_REGION: "IMAGE_LOAD_IMAGE_REGION",
  FORGET_IMAGE_REGION: "FORGET_IMAGE_REGION",
  UPDATE_IMAGE_SIZE: "UPDATE_IMAGE_SIZE",
  LOAD_ANNOTATED: "LOAD_ANNOTATED",
  LOAD_NONANNOTATED: "LOAD_NONANNOTATED",
  CLEAR_CACHED_IMAGE: "CLEAR_CACHED_IMAGE",
  LOAD_ERROR: "LOAD_ERROR",
}

export const VIDEO = {
  INDEX: "VIDEO_INDEX",
  LOADING: "VIDEO_LOADING",
  DID_LOAD: "VIDEO_DID_LOAD",
  LOAD_INDEX: "VIDEO_LOAD_INDEX",
  BROWSE_TO: "VIDEO_BROWSE_TO",
}

export const EDITOR = {
  INDEX: "EDITOR_INDEX",
  LOADING: "EDITOR_LOADING",
  DID_LOAD: "EDITOR_DID_LOAD",
  LOAD_INDEX: "EDITOR_LOAD_INDEX",
  SET_NODE: "EDITOR_SET_NODE",
  BROWSE_TO: "EDITOR_BROWSE_TO",
  LOAD_ITEM: "EDITOR_LOAD_ITEM",
  FORGET_ITEM: "EDITOR_FORGET_ITEM",
  SET_SELECTED_ID: "EDITOR_SET_SELECTED_ID",
  CLEAR_SELECTED_ID: "EDITOR_CLEAR_SELECTED_ID",
}
