# Generated by Django 2.0.1 on 2018-03-13 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('t', models.FloatField(default=0.0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='images.Image')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hierarchy.Hierarchy')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
