# Generated by Django 2.0.1 on 2018-05-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_imageregion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageregion',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='hierarchy.Hierarchy'),
        ),
    ]
