# Generated by Django 2.0.1 on 2018-03-13 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=24)),
                ('fn', models.CharField(max_length=80)),
                ('ext', models.CharField(blank=True, max_length=4)),
                ('original_fn', models.CharField(blank=True, max_length=80)),
                ('from_sa', models.BooleanField(default=False)),
                ('sa_hash', models.CharField(blank=True, max_length=80)),
                ('source_url', models.CharField(blank=True, max_length=200)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('graphic', models.BooleanField(default=False)),
                ('tags', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
