# Generated by Django 2.0.1 on 2018-03-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
