# Generated by Django 2.0.1 on 2018-03-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='annotated',
            field=models.BooleanField(default=False),
        ),
    ]
