# Generated by Django 2.0.1 on 2018-04-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_image_region_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='phash',
            field=models.BigIntegerField(default=False),
        ),
    ]
