# Generated by Django 2.0.1 on 2018-04-09 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_image_image_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagegroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
