# Generated by Django 2.0.1 on 2018-04-12 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_auto_20180409_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='images.ImageGroup'),
        ),
        migrations.AlterField(
            model_name='imagegroup',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
