# Generated by Django 2.0.1 on 2018-07-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_auto_20180412_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='base_href',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='image',
            name='frame',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
