# Generated by Django 2.0.1 on 2018-10-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_auto_20180703_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='verified',
            field=models.BooleanField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
