# Generated by Django 2.0.1 on 2018-03-13 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=80)),
                ('name_ar', models.CharField(blank=True, max_length=80)),
                ('slug', models.CharField(max_length=80)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('synonyms', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_set', to='hierarchy.Hierarchy')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
