# Generated by Django 2.0.1 on 2018-03-19 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_description'),
        ('hierarchy', '0004_auto_20180319_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchy',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image'),
        ),
    ]
