# Generated by Django 2.0.1 on 2018-03-22 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0005_hierarchy_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchy',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image'),
        ),
    ]
