# Generated by Django 2.0.1 on 2018-03-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_image_region_count'),
        ('editor', '0003_imageregion_user'),
        ('hierarchy', '0006_auto_20180322_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchy',
            name='images',
            field=models.ManyToManyField(related_name='images', through='editor.ImageRegion', to='images.Image'),
        ),
    ]
