# Generated by Django 2.0.1 on 2018-05-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0008_hierarchy_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchy',
            name='region_count',
            field=models.IntegerField(default=0),
        ),
    ]
